Models Changed!
lssc/Legacy-LSSCOJ pull request #3
Opened 2020-07-19 12:13 UTC by cccbeginner

If thers are some mistakes, tell me.

2020-07-19 14:55 UTC, daviddaytw reviewed
@cccbeginner There are two questions, please answer.

2020-07-19 14:55 UTC, dj6082013 commented on web/models/user_info.js
> +    allowNull: true,
Can you explain this? Why there's a `contest_id` ?

2020-07-19 14:55 UTC, dj6082013 commented on web/models/admins.js
> +});
What is the reason to use a table but a single column in the `user_info` model?
Is it for the future feature?

2020-07-19 15:00 UTC, cccbeginner commented on web/models/user_info.js
> +    allowNull: true,
Umm...
It'll be convenience & intuitive to get the contest which the user join.
Ah didn't I written in my comment before?

2020-07-19 15:06 UTC, cccbeginner commented on web/models/admins.js
> +});
In order to identify whether the current user has admin authority, I choose to store in another table.
If I store in the 'user_info' table, it would be easier for hackers to change the value, I think.

2020-07-19 16:43 UTC, dj6082013 commented on web/models/user_info.js
> +    allowNull: true,
@cccbeginner 
 But it can only store ONE value, how can storing ONE value to know what contests user joined?

I think it’s better to just run SQL query on `contest_registrations` to get the information.

2020-07-19 16:48 UTC, daviddaytw requested changes

2020-07-19 16:48 UTC, dj6082013 commented on web/models/user_info.js
>    quote: {
I recommend change `quote` to `motto` for better scenarios.

2020-07-21 09:34 UTC, daviddaytw approved these changes

2020-07-21 09:37 UTC, merged