8/1 commit
lssc/Legacy-LSSCOJ pull request #4
Opened 2020-08-01 14:19 UTC by cccbeginner

Finish almost everything about problems & users.
Add ids to few of tables.
If I miss something, pls tell me or change your self.

2020-08-02 09:56 UTC, daviddaytw requested changes
Few problem to fix. Please fix it then I will continue the review.

2020-08-02 09:56 UTC, dj6082013 commented on web/app.js
> +
Please write in controller instead of overriding `req` parameter

2020-08-02 09:56 UTC, dj6082013 commented on web/models/index.js
> +sequelize.sync({ force: false });
Why change this? If you don't want to force sync just remove the `{ force: true }` will to the trick.

2020-08-02 09:56 UTC, dj6082013 commented on web/models/user_msg.js
> +    type: DataTypes.INTEGER.UNSIGNED,
Please use monotonic format.

2020-08-02 09:56 UTC, dj6082013 commented on web/app.js
> +
Please use a controller instead of override the `req` variable.

2020-08-02 09:56 UTC, dj6082013 commented on web/models/problems_samples.js
> +  },
Why give ids to this model?

2020-08-02 09:56 UTC, dj6082013 commented on web/models/problems_tags.js
>    },
Why give ids to this model?

2020-08-02 09:56 UTC, dj6082013 commented on web/models/user_msg.js
> +    type: DataTypes.INTEGER.UNSIGNED,
Please use monotonic format.

2020-08-02 09:56 UTC, dj6082013 commented on web/views/problem/settings.pug
> +                h3(class='card-title') modify problem
Please check case.

2020-08-02 09:56 UTC, dj6082013 commented on web/views/problem/settings.pug
> +            h3(class='card-title') modify samples
Please check case.

2020-08-02 09:56 UTC, dj6082013 commented on web/views/problem/settings.pug
> +            h3(class='card-title') create sample
Please check case.

2020-08-02 09:56 UTC, dj6082013 commented on web/views/problem/settings.pug
> +            br
Do not use `br` html tag.

2020-08-02 10:01 UTC, dj6082013 commented on web/views/login.pug
> -              input(type='text', class='form-control', id='input-institution', name='institution')
Please add this back.

2020-08-02 10:37 UTC, cccbeginner commented on web/models/problems_samples.js
> +  },
To identify different sample in the same problem easier.
Or, do you prefer let 'order' to be identifier?

2020-08-02 10:38 UTC, cccbeginner commented on web/models/problems_tags.js
>    },
Same reason as above.

2020-08-02 10:51 UTC, cccbeginner commented on web/views/login.pug
> -              input(type='text', class='form-control', id='input-institution', name='institution')
Should I bring back 'institution' column in the 'user_info' model and add it to profile page and controllers?

2020-08-02 11:41 UTC, dj6082013 commented on web/models/problems_samples.js
> +  },
Yes I want to use `order` instead so that user can easier change the order.

2020-08-02 11:42 UTC, dj6082013 commented on web/models/problems_tags.js
>    },
I don’t think we need to identify the relation of problem and tags.

2020-08-02 11:45 UTC, dj6082013 commented on web/views/login.pug
> -              input(type='text', class='form-control', id='input-institution', name='institution')
Yes, thanks!

2020-08-02 11:50 UTC, cccbeginner commented on web/models/problems_tags.js
>    },
OK. 
I'll use `tag` to identify & search certain tag.

2020-08-03 14:01 UTC, daviddaytw approved these changes
Nice work!

2020-08-03 14:02 UTC, merged